POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjE4MDY2Yi1lN2ZiLTQzOTItYjM4Ny0zZWNlM2E0YjNiZmYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTc5ODA2OX0._8P6QBqMNhwTc_Rg7Q2p1ZHCgM3JayI9YanbCDJiwN0

{
  "title": "Curso de React"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/b5696151-5a59-4354-ae6e-4c8aa470ca9c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMjE4MDY2Yi1lN2ZiLTQzOTItYjM4Ny0zZWNlM2E0YjNiZmYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTc5ODA2OX0._8P6QBqMNhwTc_Rg7Q2p1ZHCgM3JayI9YanbCDJiwN0

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "matheus.santos@live.com",
  "password": "123456"
}


###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "matheus",
  "email": "matheus.santos@live.com",
  "password": "123456",
  "role": "manager"
}
