POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjFjYTMyYS0wYWUyLTRhOWQtOTE4Mi05MTU1YjFiNDI4ZWUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1Njg1MjU1N30.3TUJn2ctcVRX5CzcJc-_jBpYSKL9kEkB_n6h_ytmYdk

{
  "title": "Curso de React"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/6e0081b6-693c-46e1-bc1a-05f04d1ebfa1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NWQxOTI1ZC0zYWY1LTQ5NDctOWVkMS00NDg3NTVlM2Y1NjkiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NzQ1MTc3NSwiZXhwIjoxNzU3NDUxODM1fQ.Fu1nKeVU1ofDNz4_LdY0zH_QD5lKliRLkGVrc7Vq_bA
###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "matheus.santos1@live.com",
  "password": "123456"
}


###

POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "matheus",
  "email": "matheus.santos1@live.com",
  "password": "123456",
  "role": "manager"
}


###

POST http://localhost:3333/enrollments/d0eb0200-6a17-4dc9-a978-35256f9b1c0a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjFjYTMyYS0wYWUyLTRhOWQtOTE4Mi05MTU1YjFiNDI4ZWUiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NjkzNjczNX0.hs5NuOuPFTcgKp3uwoqIKuPQeXgm1yAhCApulIaWheU


